function data = doRename(data, folding)
%rename to shorter fields, for analysis of folded or unfolded data.
    if ~exist('folding', 'var') || ismepty(folding)
        folding = true;
    end
    if folding
        data = rename(data, ...
                      'target_spacing', 'spacing', ...
                      'folded_direction_content', 'content', ...
                      'folded_displacement', 'dx', ...
                      'folded_response_with_carrier', 'response');
    else
        data = rename(data, ...
                      'target_spacing', 'spacing', ...
                      'abs_direction_content', 'content', ...
                      'abs_displacement', 'dx', ...
                      'abs_response_cw', 'response');
    end
end