#!/usr/bin/env python2.7

import re
import os
import sys
import shutil

files = set()

destination = sys.argv[1]

for file in sys.argv[2:]:
    with open(file) as f:
        files.update(re.findall('src="([^"]*)"', f.read()))

for f in files.union(sys.argv[2:]):
    destfile = os.path.join(destination, f)
    if not os.path.exists(os.path.dirname(destfile)):
        os.makedirs(os.path.dirname(destfile))
    print("{} -> {}".format(f, destfile))
    shutil.copyfile(f, destfile)
