#!/usr/bin/env python
import sys

def main(input, output):
    with file(input, "r") as i, file(output, "w") as o:
        write = False
        for line in iter(i.readline, ''):
            if line.startswith("\\begin{document"):
                write=True
                continue
            if line.startswith("\\end{document"):
                write=False
                continue
            if write:
                o.write(line)

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
